export const BONUS_EVENTS = {
  crowdPressure: {
    label: "CROWD PRESSURE",
    eligibility: "Level 1, 15 clean dubplates, no hazard in the streak",
    trigger: "Clean-streak threshold reaches 15",
    recurrence: "once per Level 1 run",
    priority: 90,
    cooldown: "none",
    gameplayState: "LEVEL_1",
    pausesGameplay: true,
    resume: "Return to the same Level 1 run unless it has already reached 25 records",
    comboEffect: "preserves the earned run state",
    visualAsset: "no-request-splash-overlay / Crowd Pressure stage",
  },
  wrongTune: {
    label: "WRONG TUNE",
    eligibility: "Two consecutive phone hazards",
    trigger: "Second phone collision",
    recurrence: "recurring after the two-hit pattern resets",
    priority: 80,
    cooldown: "sequence duration",
    gameplayState: "LEVEL_1 or LEVEL_2",
    pausesGameplay: true,
    resume: "Record-spin return to the active level",
    comboEffect: "hazard resets combo",
    visualAsset: "crowd-anger-overlay",
  },
  policeSeizure: {
    label: "POLICE SEIZED MIXER",
    eligibility: "Two consecutive cop hazards",
    trigger: "Second cop collision",
    recurrence: "recurring after the two-hit pattern resets",
    priority: 85,
    cooldown: "sequence duration",
    gameplayState: "LEVEL_1 or LEVEL_2",
    pausesGameplay: true,
    resume: "Record-spin return with mixer recovery active",
    comboEffect: "hazard resets combo",
    visualAsset: "police-seizure-overlay",
  },
  tooHighToPlay: {
    label: "TOO HIGH TO PLAY",
    eligibility: "Two consecutive pill hazards",
    trigger: "Second pill collision",
    recurrence: "recurring after the two-hit pattern resets",
    priority: 85,
    cooldown: "sequence duration",
    gameplayState: "LEVEL_1 or LEVEL_2",
    pausesGameplay: true,
    resume: "Record-spin return to the active level",
    comboEffect: "hazard resets combo",
    visualAsset: "pill-overload-overlay",
  },
  mixerDamage: {
    label: "MIXER DAMAGED",
    eligibility: "Any active hazard collision",
    trigger: "Equipment condition worsens",
    recurrence: "recurring until game over",
    priority: 70,
    cooldown: "none",
    gameplayState: "PLAYING",
    pausesGameplay: false,
    resume: "State changes to RECOVERY after impact feedback",
    comboEffect: "hazard resets combo",
    visualAsset: "damage-feedback / mixer-recovery-status",
  },
  mixerRepair: {
    label: "MIXER REPAIRED",
    eligibility: "Mixer damaged and three dubplates caught",
    trigger: "Third recovery dubplate",
    recurrence: "recurring after later damage",
    priority: 70,
    cooldown: "none",
    gameplayState: "RECOVERY",
    pausesGameplay: false,
    resume: "Return to PLAYING through normal game-loop state",
    comboEffect: "does not reset combo",
    visualAsset: "mixer-recovery-status / mixerRepairBurst",
  },
  recordCrate: {
    label: "RECORD CRATE",
    eligibility: "Three mixer pickups and reward spacing clear",
    trigger: "Third mixer pickup",
    recurrence: "recurring",
    priority: 35,
    cooldown: "reward-spacing guard",
    gameplayState: "PLAYING",
    pausesGameplay: false,
    resume: "immediate",
    comboEffect: "does not reset combo",
    visualAsset: "crate-bonus-overlay",
  },
  headphonesReady: {
    label: "HEADPHONES READY",
    eligibility: "Three turntable pickups and reward spacing clear",
    trigger: "Third turntable pickup",
    recurrence: "recurring",
    priority: 35,
    cooldown: "reward-spacing guard",
    gameplayState: "PLAYING",
    pausesGameplay: false,
    resume: "immediate",
    comboEffect: "does not reset combo",
    visualAsset: "headphones-bonus-overlay",
  },
  boh: {
    label: "BOH! BOH! BIG UP",
    eligibility: "First Level 1 objective count at five",
    trigger: "Fifth Level 1 dubplate",
    recurrence: "once per run",
    priority: 30,
    cooldown: "run guard",
    gameplayState: "LEVEL_1",
    pausesGameplay: false,
    resume: "immediate",
    comboEffect: "adds reward score only",
    visualAsset: "selector-salute-overlay",
  },
  wheelItUp: {
    label: "WHEEL IT UP",
    eligibility: "Combo 30 and reward spacing clear",
    trigger: "Thirty-hit combo",
    recurrence: "once per run",
    priority: 30,
    cooldown: "run guard",
    gameplayState: "PLAYING",
    pausesGameplay: false,
    resume: "immediate",
    comboEffect: "adds reward score only",
    visualAsset: "wheel-it-up-overlay",
  },
  rewind: {
    label: "REWIND",
    eligibility: "Combo 18",
    trigger: "Eighteen-hit combo",
    recurrence: "once per run",
    priority: 30,
    cooldown: "run guard",
    gameplayState: "PLAYING",
    pausesGameplay: true,
    resume: "record-spin return to active level",
    comboEffect: "does not reset combo",
    visualAsset: "rewind-reward-overlay",
  },
  runRiddim: {
    label: "RUN THE RIDDIM",
    eligibility: "Level 2 objective count at fifteen",
    trigger: "Fifteenth Level 2 item",
    recurrence: "once per Level 2 run",
    priority: 40,
    cooldown: "run guard",
    gameplayState: "LEVEL_2",
    pausesGameplay: false,
    resume: "immediate",
    comboEffect: "adds reward score only",
    visualAsset: "run-riddim-overlay",
  },
  downloadUnlock: {
    label: "DOWNLOAD UNLOCK",
    eligibility: "Level 1 objective count reaches 25 and download is locked",
    trigger: "Twenty-fifth Level 1 dubplate",
    recurrence: "once per browser session",
    priority: 100,
    cooldown: "session guard",
    gameplayState: "LEVEL_COMPLETE",
    pausesGameplay: true,
    resume: "Level 2 transition after unlock reveal",
    comboEffect: "preserves earned score",
    visualAsset: "unlock-overlay",
  },
} as const;

export type BonusEventId = keyof typeof BONUS_EVENTS;

export type BonusEventDiagnostic = {
  eligible: boolean;
  blocked: boolean;
  blockReason: string;
  triggerCount: number;
  lastTriggerTime: number | null;
  currentGameState: string;
};

export type BonusEventDiagnostics = Record<BonusEventId, BonusEventDiagnostic>;

export function createBonusEventDiagnostics(gameplayState = "READY"): BonusEventDiagnostics {
  return Object.fromEntries(
    Object.keys(BONUS_EVENTS).map((event) => [event, {
      eligible: false,
      blocked: true,
      blockReason: "not evaluated yet",
      triggerCount: 0,
      lastTriggerTime: null,
      currentGameState: gameplayState,
    }]),
  ) as BonusEventDiagnostics;
}
